### ISSUE TITLE
No issues, just playing around

### ISSUE THREAD

**Issue by OrionRandD** [santiagobasulto/ipython-gpt#1]
Great idea!
I have tested it in Emacs vterm and eshell.
It plays ok in vterm, but eshell.
In eshell it jumps one space all the time, e.g.,
if I write "%%chat", it does "%% chat", then I have to delete the space between "%% and chat"

**Comment by santiagobasulto** [comment]
Thanks! It's been a long time since I've used Emacs. I'll take a look to see if it's something we can improve from our side.
