### ISSUE TITLE
free API key not working?

### ISSUE THREAD

**Issue by BuddyVolly** [santiagobasulto/ipython-gpt#9]
Dear Santiago, 

I am trying to set this up, using a free API token. I haven't used any of API free grant. Still I don't seem to get it work. 
Neither with setting an environmental variable, nor with the openai-api-key option. 

Is there anything wrong in using the free API key? Or what could be the reason?

That's the error I am getting:
APIResponseException: Failed API Request 'POST /v1/chat/completions'

Thanks,
Andreas

**Comment by santiagobasulto** [comment]
Hello Andreas. Can you try running the `%chat_models` directive? We have to understand if it's an issue with authentication or OpenAI's API (that is not working very consistently lately).

**Comment by BuddyVolly** [comment]
Hi thnks for the quick response, 

ok, now I am getting this APIResponseException: Failed API Request 'POST /v1/chat/completions'. Got 429: You exceeded your current quota, please check your plan and billing details.

but I've never used the API before and inside openai it shows me I haven't used any of my 18$ quota. Maybe free accounts are blocked?

**Comment by BuddyVolly** [comment]
p.s. %chat_models works

**Comment by santiagobasulto** [comment]
That's strange. Can you try re-generating the API Token? Using a new one to make sure it's tied to the billing account with the $18 quota.

**Comment by santiagobasulto** [comment]
@BuddyVolly I'm closing this one as it was probably an issue with API quota. Re-open it if still experiencing the issues.
